### ISSUE TITLE
Connect to database with pdo

### ISSUE THREAD

**Issue by aalfiann** [crazy-goat/slim-reactor#1]
I have test this slim-reactor and working prefectly without make connection to database. 

But when i try to make connection to database with pdo through dependency injection, slim-reactor is always loading for a long time. 

Is this support pdo database or not?

**Comment by s2x** [comment]
Connection to mysql may take a while, so you should not create a connection in the controller. Try creating PDO connection only once and pass it to controller. Se code bellow:
```php
use CrazyGoat\SlimReactor\SlimReactor;
use Slim\{Http\Request, Http\Response};

include 'vendor/autoload.php';
$slimReactor  = new SlimReactor();

// create connection outside controller
$dbh = new \PDO('mysql:host=127.0.0.1;dbname=test', 'test', 'test');

// pass $dbh into controller using 'use'
$slimReactor->getApp()->get('/', function (Request $request, Response $response) use ($dbh) {

    $stmt = $dbh->query('select * from test_table LIMIT 1');

    return $response->write('db says: '.$stmt->fetchColumn(1));
});

echo 'Server is listening on socket: '.$slimReactor->getSocket()->getAddress()."\n";

$slimReactor->run();
```

**Comment by aalfiann** [comment]
Thanks, it works now.  

I will close this issue. 

This is awesome.
